lib/primitive_bank_web/router.ex
defmodule PrimitiveBankWeb.Router do
  use PrimitiveBankWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PrimitiveBankWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController

    scope "/bank_operations" do
      get "/", BankOperationController, :index
      get "/charge", BankOperationController, :new_charge
      post "/charge", BankOperationController, :charge
      get "/add", BankOperationController, :new_add
      post "/add", BankOperationController, :add
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PrimitiveBankWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PrimitiveBankWeb.Telemetry
    end
  end
end

lib/primitive_bank_web/controllers/bank_operation_controller.ex
defmodule PrimitiveBankWeb.BankOperationController do
  require IEx
  use PrimitiveBankWeb, :controller

  alias PrimitiveBank.Accounts
  alias PrimitiveBank.Accounts.User

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def new_charge(conn, _params) do
    render(conn, "charge.html")
  end

  def charge(conn, %{"username" => username, "amount" => amount}) do
    Accounts.get_by_username(username)
    |> Accounts.charge_amount(amount)

    render(conn, "index.html")
  end

  def new_add(conn, params) do
    render(conn, "add.html")
  end

  def add(conn, %{"username" => username, "amount" => amount}) do
    Accounts.get_by_username(username)
    |> Accounts.add_amount(amount)

    render(conn, "index.html")
  end
end

lib/primitive_bank_web/views/bank_operation_view.ex
defmodule PrimitiveBankWeb.BankOperationView do
  use PrimitiveBankWeb, :view
end

lib/primitive_bank_web/templates/bank_operation/add.html.eex
<h3>Add money</h3>
<%= form_for @conn, Routes.bank_operation_path(@conn, :add), fn f -> %>
    <label>
        Username: <%= text_input f, :username %>
    </label>

    <label>
        Amount: <%= number_input f, :amount %>
    </label>

<%= submit "Add! :)" %>
<% end %>

lib/primitive_bank_web/templates/bank_operation/charge.html.eex
<%= form_for @conn, Routes.bank_operation_path(@conn, :charge), fn f -> %>
<label>
    Username: <%= text_input f, :username %>
</label>

<label>
    Amount: <%= number_input f, :amount %>
</label>

        <%= submit "Charge! :(" %>
<% end %>

lib/primitive_bank_web/templates/bank_operation/index.html.eex
<h1>Bank Operations</h1>

<a href="<%= Routes.bank_operation_path(@conn, :new_charge) %>">Charge</a>
<a href="<%= Routes.bank_operation_path(@conn, :new_add) %>">Add</a>